.\" Manual for genffcom (silentcast)
.TH man 1 "09 November 2014" "" "Linux User's Manual"
.SH NAME 
genffcom \- generate a bash script to record the user's screen at 8 fps
.SH SYNOPSIS
.BI "genffcom " "[-h -a area -r rate# -d dir] {silentcast#}"

.SH DESCRIPTION
genffcom generates a bash script in the current directory
called ffcom containing an ffmpeg command that will record
a silent mkv video at a default rate of 8 frames per second.
Execute the generated script with 

	bash ffcom

in a terminal, and exit by clicking the stop icon in the
notification area. Ignore instructions from ffmpeg about
stopping it with q - it won't work. If you don't have a
notification area, you can still stop it with ctrl-c in
the terminal where it is running.
.SH OPTIONS

.BR "-h " "display this help and exit "

.BR "-a " "area area is one of the following letters:" 
 
	f t i e

and have the following meanings:

.BR "f " ": Fullscreen "

.BR "t " ": Transparent Window Interior"

.BR "i " ": Interior of a Window"

.BR "e" " : Entirety of a Window"

(default is Interior of a Window)

.BR "-r rate#" " set frames per second to " rate# ", a natural number (2 to 120) (default is 8 frames per second)"

.BR "-d dir" " directory where the bash script ffcom
will be created (default is the current directory)"

.BR "silentcast#" " is a single digit indicating how many instances of silentcast are running. silentcast limits it to 1 or 2, but can be set to anything or left blank if genffcom is called outside of silentcast"

.BR "genffcom" " is normally called from " "silentcast" "(1), but can be called directly or from another script."

.SH SEE ALSO
.BR "silentcast" "(1), " "temptoanim" "(1)"

.SH BUGS

No known bugs.

.SH AUTHOR

.BR "genffcom" " was written by Colin Keenan <colinnkeenan@gmail.com>. This manual page was written by Seth Johnson <sethj0438@gmail.com>."
