#!/bin/bash
# Output from genffcom for screencast#=

printf "Click OK when ready to start recording.

To Stop Recording: 
Click the stop icon in the Notification Area" \
| yad ---text-info --on-top --center --width=440 --height=280 --wrap --title="Get Ready" --window-icon="media-record" --text="\
<b>SILENTCAST                 </b><span font='24' color='green'>1</span>"
[ "$?" -ne "0" ] && exit 1 #Cancel was clicked

ffmpeg -f x11grab -s 1280x720 -r 8 -i :0.0+0,26 -c:v ffvhuff -an -y temp.mkv & ffmpegPID=$!
yad --notification --image="stop" --text=""
kill $ffmpegPID
