#!/bin/bash
# Get the coordinates of the active window's
#    top-left corner, and the window's size.
#    This excludes the window decoration.
# --full means get current screen resolution
#    instead of active window's size.
# Put results in a bash file ffcom containing an
#    ffmpeg command that will record a silent 
#    mkv video at 8 frames per second
# $2 only matters if it's --full, then the entire
#    screen is used for the size of recording
# $1 is which instance of silentcast is running
#    because it is allowed to do a silentcast
#    of a silentcast. 
guake -t
unset x y w h
if [ "$2" == '--full' ]
then
	w=$(xrandr --current | grep '* ' | uniq | awk '{print $1}' |  cut -d 'x' -f1)
	h=$(xrandr --current | grep '* ' | uniq | awk '{print $1}' |  cut -d 'x' -f2)
else
        zenity --info --text="SILENTCAST"$1": Click OK when ready to generate ffcom - i.e. when you've got the next active window sized correctly"
        sleep 1
        eval $(xwininfo -id $(xdotool getactivewindow) |
          sed -n -e "s/^ \+Absolute upper-left X: \+\([0-9]\+\).*/x=\1/p" \
                 -e "s/^ \+Absolute upper-left Y: \+\([0-9]\+\).*/y=\1/p" \
                 -e "s/^ \+Width: \+\([0-9]\+\).*/w=\1/p" \
                 -e "s/^ \+Height: \+\([0-9]\+\).*/h=\1/p" )
fi
echo '#!/bin/bash
# Output from genffcom when castnum='$1'
zenity --info --text="SILENTCAST '$1': click OK when ready to start recording. Toggle Guake and press q to stop recording."
ffmpeg -f x11grab -s '$w'x'$h' -r 8 -i :0.0+'$x','$y' -c:v ffvhuff -an -y temp.mkv' > ffcom
chmod +x ffcom
