#!/bin/bash
install -D -m755 silentcast /usr/bin/silentcast
install -D -m755 genffcom /usr/bin/genffcom
install -D -m755 temptoanim /usr/bin/temptoanim
install -D -m755 transparent_window.py /usr/share/silentcast/transparent_window.py
install -D -m755 unity_indicator.py /usr/share/silentcast/unity_indicator.py
install -D -m755 silentcast.desktop /usr/share/applications/silentcast.desktop
install -D -m755 localREADME.md /usr/share/doc/silentcast/README.md
install -m755 *png /usr/share/doc/silentcast
install -m755 *gif /usr/share/doc/silentcast
