#!/bin/bash
echo Copying files...
install -D -m755 silentcast /usr/bin/silentcast
install -D -m755 genffcom /usr/bin/genffcom
install -D -m755 temptoanim /usr/bin/temptoanim
install -D -m755 transparent_window.py /usr/share/silentcast/transparent_window.py
install -m755 unity_indicator.py /usr/share/silentcast
install -m755 stop?.png /usr/share/silentcast
install -D -m755 silentcast.png /usr/share/pixmaps/silentcast.png
install -D -m755 silentcast.desktop /usr/share/applications/silentcast.desktop
install -D -m755 README.md /usr/share/doc/silentcast/README.md
install -m755 *png /usr/share/doc/silentcast
install -m755 *gif /usr/share/doc/silentcast
echo Install complete
echo "NOTE==>The command is 'silentcast'. See /usr/share/docs/silentcast/README.md or https://github.com/colinkeenan/silentcast/#silentcast for full instructions and tips."

