#!/bin/bash
unset dirname_of_arg 
install_dir="$HOME/.silentcast"
show_help() {
cat << EOF

Usage: no_root_install [-h -d PATH]

    -h          display this help and exit
    -d PATH	install Silentcast into PATH directory, 
                creating the directory if it doesn't exist
		(defaults to $HOME/.silentcast)

EOF
}

OPTIND=1
while getopts ":hd:" opt
do 
	echo $OPTARG # I don't know why I have to echo $OPTARG to get it assigned, but I do
	case $opt in
		h)
			show_help
			exit 0
			;;
		d)
			arg="$OPTARG"
			[ "${arg:0:1}" = \~ ] && arg=$HOME/${arg:2} # in case it's "~/..." replace ~ with $HOME
			dirname_of_arg=$(dirname "$arg")
			if (touch "$arg/foo" 2>/dev/null && rm -f "$arg/foo") || \
				(touch "$dirname_of_arg/foo" 2>/dev/null && rm -f "$dirname_of_arg/foo")
			then
				install_dir="$arg"
			else
				echo Neither "$arg" nor "$dirname_of_arg" can be written to. Either 
				echo it requires root, or is on a read only device.
				exit -1
			fi
			;;
		\?) 
			echo "Invalid option: -$OPTARG  ('no_root_install -h' for help)" >&2
			exit 1
			;;
	       	:)
		       	echo "Option -$OPTARG requires an argument." >&2
		       	exit 1
		       	;;

	esac
done
shift "$((OPTIND-1))" # get rid of everything just processed leaving anything else as $1 $2 etc.

if ! [ "$1" = "" ]
then
	show_help
	exit -1
fi

echo Making desktop launcher in "$HOME"/.local/share/applications ...
install -d "$HOME/.local/share/applications"
cat > "$HOME/.local/share/applications/no_root_silentcast.desktop" <<EOF
[Desktop Entry]
Name=Silentcast
Comment=To uninstall: rm -r $(printf %q "$install_dir"); rm "$HOME/.local/share/applications/no_root_silentcast.desktop" video record your screen and make it into an animated gif, webm, or mp4 screencast
Exec="$install_dir/silentcast"
Path=$install_dir
Type=Application
StartupNotify=true
Icon=$install_dir/silentcast.png
Categories=Graphics;AudioVideo;
EOF

echo Copying files to "$install_dir" ...
install -d "$install_dir"
install * "$install_dir"
echo
echo Install complete. This source directory can be deleted if desired. 
echo
echo Uninstall with the following commands:
echo
echo rm -r $(printf %q "$install_dir") # escape the spaces so copy and pasting this command does what it's supposed to
echo rm "$HOME/.local/share/applications/no_root_silentcast.desktop"
echo
echo NOTE: Find the Silentcast launcher under Multimedia or Graphics in your desktop menu or under silentcast from search. See "$install_dir/README.md" or https://github.com/colinkeenan/silentcast/#silentcast for full instructions and tips.

# End of file
