#!/bin/bash

unset fullscreen,fps,f,rate
#defaults
fullscreen=FALSE
fps=8
f=""
rate=""

arg_form=`yad --form \
	--title="Silentcast" \
	--separator="," \
	--field="Fullscreen":CHK \
	--field="Frames per second" \
	FALSE 8`
fullscreen="$(awk -F, '{print $1}' <<<"$arg_form")"
fps="$(awk -F, '{print $2}' <<<"$arg_form")"

if [ "$fullscreen" = TRUE ]
then
       f="-f"
fi

if [ $fps -ne 8 ]
then
	rate="-r"$fps
fi

`silentcast $f $rate`
