#!/bin/bash

show_help() {
cat << EOF
silentcast creates a silent video, silentcast/temp.mkv,
and an animated gif, silentcast/anim.gif, recording an
area of the screen.

silentcast runs 2 other bash scripts that are part of the 
same package: genffcom and temptoanim
Look at those help outputs for more information. Even better,
view /usr/share/doc/silentcast/README.md with a markdown
viewer and get an animated gif demo made with silentcast, as
well as a step by step guide and a list of tips.
EOF
}

if [ "$1" = "-h" ]
then
	show_help
	exit 0
fi

unset fps fullscreen ffcoms_running f rate arg_form
#defaults
fps=8
fullscreen=FALSE
ffcoms_running=0
f=""
rate=""

arg_form=`yad --form --on-top --center\
	--title="Silentcast" \
	--window-icon="media-record" \
	--text='<tt>\
  <span background="white">For a demo, guide, and list of tips,</span>\n\
  <span background="white">install a markdown viewer extension </span>\n\
  <span background="white">to your web browser and click:      </span>\n\
  <span background="white"><a href="file:///usr/share/doc/silentcast/README.md">\
             README.md              </a></span></tt>\n\n\
If Fullscreen is not checked, the area defined by an active window chosen later will be recorded. '\
	--separator="," \
	--field="Fullscreen":CHK \
	--field="Frames per second" \
	FALSE 8`
[ "$?" -ne "0" ] && exit 1 #Cancel was clicked
fullscreen="$(awk -F, '{print $1}' <<<"$arg_form")"
fps="$(awk -F, '{print $2}' <<<"$arg_form")"

if [ "$fullscreen" = TRUE ]
then
       f="-f"
fi

if [ "$fps" -ne 8 ]
then
	rate="-r"$fps
fi

cd
ffcoms_running=`pgrep -f ffcom | wc -l`
if [ $ffcoms_running -gt 0 ]
then
	if [ $ffcoms_running -gt 1 ]
	then
		echo "You are already doing a recording of a recording. Further nesting of silentcasts is not supported."
		exit -1
	else
		mkdir -p silentcast/silentcast
		castnum=2
	fi
else
	mkdir -p silentcast
	castnum=1
fi

if [ $castnum -eq 1 ]
then
	cd ~/silentcast
else
	cd ~/silentcast/silentcast
fi

genffcom $f $rate $castnum 
[ "$?" -ne "0" ] && exit 1 #Cancel was clicked in genffcom
bash ffcom
[ "$?" -ne "0" ] && exit 1 #Cancel was clicked in ffcom
temptoanim $castnum $fps

# End of file
