#!/bin/bash
cd
ffcoms_running=`pgrep -x ffcom | wc -l`
if [ $ffcoms_running -gt 0 ]
then
	if [ $ffcoms_running -gt 1 ]
	then
		echo "You are already doing a silentcast of a silentcast. Further nesting of silentcasts is not supported."
		exit -1
	else
		mkdir -p silentcast/silentcast
		castnum=2
	fi
else
	mkdir -p silentcast
	castnum=1
fi

if [ $castnum -eq 1 ]
then
	cd ~/silentcast
else
	cd ~/silentcast/silentcast
fi
genffcom $1 $castnum
./ffcom
temptoanim $castnum
