#!/bin/bash

show_help() {
cat << EOF
silentcast creates a silent video, silentcast/temp.mkv,
and an animated gif, silentcast/anim.gif, recording an
area of the screen.

silentcast runs 2 other bash scripts that are part of the 
same package: genffcom and temptoanim
Look at those help outputs for more information. Even better,
view /usr/share/doc/silentcast/README.md with a markdown
viewer and get an animated gif demo made with silentcast, as
well as a step by step guide and a list of tips.
EOF
}

if [ "$1" = "-h" ]
then
	show_help
	exit 0
fi

unset fps area_choice area ffcoms_running rate arg_form
#defaults
fps=8
ffcoms_running=0
area_choice="Fullscreen"
area="f"

arg_form=`yad --form --on-top --center\
	--title="Silentcast" \
	--window-icon="media-record" \
	--text='<tt>\
  <span background="white">                                        </span>\n\
  <span background="white">  For a demo, guide, and list of tips,  </span>\n\
  <span background="white">  install a markdown viewer extension   </span>\n\
  <span background="white">  to your browser and click: <a href="file:///usr/share/doc/silentcast/README.md">README.md</a>  </span>\n\
  <span background="white">                                        </span></tt>'\
  	--separator="," \
	--field="Area to be recorded":CB \
	--field="Frames per second" \
	"Fullscreen"!"Transparent Window Interior"!"Interior of a Window"!"Entirety of a Window" 8`
[ "$?" -ne "0" ] && exit 1 #Cancel was clicked

area_choice="$(awk -F, '{print $1}' <<<"$arg_form")"
fps="$(awk -F, '{print $2}' <<<"$arg_form")"         # getting second field this way only works when --separator="'"

area=${area_choice,} # lower case first letter
area=${area:0:1}     # area is now one of f t i e

ffcoms_running=`pgrep -f ffcom | wc -l`
if [ $ffcoms_running -gt 0 ]
then
	if [ $ffcoms_running -gt 1 ]
	then
		echo "You are already doing a recording of a recording. Further nesting of silentcasts is not supported."
		exit -1
	else
		mkdir -p ~/silentcast/silentcast
		castnum=2
		cd ~/silentcast/silentcast
	fi
else
	mkdir -p ~/silentcast 
	cd ~/silentcast
	castnum=1
fi
genffcom "-a"$area "-r"$fps $castnum 
[ "$?" -ne "0" ] && exit 1 #Cancel was clicked in genffcom
bash ffcom
[ "$?" -ne "0" ] && exit 1 #Cancel was clicked in ffcom
temptoanim $castnum $fps

# End of file
