#!/bin/bash
echo Deleting silentcast, genffcom, and temptoanim from /usr/bin
rm /usr/bin/silentcast
rm /usr/bin/genffcom
rm /usr/bin/temptoanim
echo Deleting directories /usr/share/silentcast and /usr/share/doc/silentcast
rm -r /usr/share/silentcast
rm -r /usr/share/doc/silentcast
echo Deleting desktop launcher from /usr/share/applications and the icon from pixmaps
rm /usr/share/applications/silentcast.desktop
rm /usr/share/pixmaps/silentcast.png
echo Removing manpages
rm /usr/share/man/man1/silentcast.1
rm /usr/share/man/man1/genffcom.1
rm /usr/share/man/man1/temptoanim.1
echo Done uninstalling Silentcast
